name: Publish webapp

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/marios-pz
  USERNAME: ${{ github.actor }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-testing:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
          ecr: auto
          logout: true

      - name: Build webapp
        run: |
            docker build .-t ${{ env.REGISTRY }}/${{ github.event.repository.name }}:${GITHUB_REF##*/}

      - name: Push webapp
        run: |
            docker push ${{ env.REGISTRY }}/${{ github.event.repository.name }}:${GITHUB_REF##*/}

